### ISSUE TITLE
this addon foces different indent in editor

### ISSUE THREAD

**Issue by christianparpart** [jbw3/language-cpp14#2]
Hi,

I am having an indent width of 2 configured; As soon as I enable this plugin, the indention width seems to be 4, no matter what I have configured in the core configuration. There seems to be also no way to force my configured indention. No configuration window seems to be appearent for the language-cpp14 plugin either.

**Comment by jbw3** [comment]
Hey,

The default tab width for language-cpp14 is 4. However, this can be changed in the plugin settings. To do this, go to Atom's Settings page and select Packages in the left menu. Then scroll down to find the language-cpp14 plugin and click on the Settings button underneath it. If you scroll down on this page you will see "Tab Length" which you will be able to change to 2.

For more info see the [Atom docs](https://atom.io/docs/v1.3.2/using-atom-atom-packages).

Thanks!

**Comment by ethanwu10** [comment]
I believe this issue should be re-opened, as it is much better, more convenient, and less confusing if the package just respected global settings instead of having its own exact duplicate in its own settings menu. This way users won't be confused because they expect the global settings to apply, when they are being overridden by the packages' own copy of the exact same settings.
